---
- name: systemctl restart restic.timer
  become: true
  ansible.builtin.systemd:
    name: "restic-{{ item.name | replace(' ', '') | string }}.timer"
    state: 'restarted'
    daemon_reload: true
    masked: false
  with_items: '{{ restic_backups_formatted }}'
  ignore_errors: true
  tags: skip_ansible_lint
  when:
    - restic_create_schedule
    - item.name is defined
    - item.scheduled | default(false)
    - ansible_service_mgr == 'systemd'
